name: Minder
description:
  en: Minder is a powerful mind mapping tool that enables you to create, edit and collaborate on various types of mind maps. After installation, you can seamlessly view and edit mind maps directly within DooTask, enhancing your workflow efficiency.
  zh: Minder 是一款功能强大的思维导图工具，支持创建、编辑和协作处理各类思维导图。安装后可在 DooTask 中无缝查看和编辑思维导图，提升工作效率。
author: DooTask
website: https://www.dootask.com/
tags:
  - 思维导图
