services:
  face:
    image: "hitosea2020/dooface:0.0.1"
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:7788"
    environment:
      TZ: "${TIMEZONE:-PRC}"
      STORAGE: mysql
      MYSQL_HOST: "${DB_HOST}"
      MYSQL_PORT: "${DB_PORT}"
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DB_NAME: "${DB_DATABASE}"
      DB_PREFIX: "${DB_PREFIX}"
      REPORT_API: "http://nginx/api/public/checkin/report"
