services:
  approve:
    image: "kuaifan/dooapprove:0.1.5"
    restart: unless-stopped
    environment:
      TZ: "${TIMEZONE:-PRC}"
      MYSQL_HOST: "${DB_HOST}"
      MYSQL_PORT: "${DB_PORT}"
      MYSQL_DBNAME: "${DB_DATABASE}"
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_Prefix: "${DB_PREFIX}approve_"
      DEMO_DATA: true
      KEY: ${APP_KEY}