name: OKR
description:
  en: A tool that helps teams efficiently set, track, and achieve objectives and key results, making goal management simple and transparent.
  zh: 一款帮助团队高效设定、跟踪和实现目标与关键结果的工具，让目标管理变得简单透明。
author: DooTask
website: https://www.dootask.com
tags:
  - 目标管理
menu_items:
  - location: application
    label:
      en: OKR Management
      zh: OKR 管理
    url: apps/okr/list
    icon: ./logo.svg

  - location: application/admin
    label:
      en: OKR Analysis
      zh: OKR 结果
    url: apps/okr/analysis
    icon: ./icon/analysis.svg

