name: Face check-in
description:
  en: Face check-in is a sign-in tool that enables face recognition functionality in DooTask's check-in page after installation, improving sign-in efficiency. It requires compatible face recognition devices to operate.
  zh: 人脸打卡是一款签到打卡工具，安装后可在 DooTask 的签到打卡页面开启人脸打卡功能，提升签到效率，需要配合指定人脸识别设备使用。
author: DooTask
website: https://www.dootask.com/
tags:
  - 签到打卡
fields:                        
  - name: SERVER_PORT
    label:
      en: Server Port
      zh: 服务端口
    type: number
    default: 7788