name: OnlyOffice
description:
  en: A comprehensive office suite that includes document, spreadsheet, and presentation editors. It provides real-time collaboration features and supports multiple file formats.
  zh: 一个功能完整的办公套件，包含文档、电子表格和演示文稿编辑器。提供实时协作功能，支持多种文件格式。
author: Community
website: https://www.onlyoffice.com/
tags:
  - 在线文档
